name: Checks
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test Deno Module
        run: deno test --coverage=cov_profile

      - name: Coverage Report
        run: deno coverage cov_profile >> $GITHUB_STEP_SUMMARY
